-- Kill Whole the DB

exec drop_all_constraints();

DROP TABLE G_CITY;
DROP TABLE G_DELAY;
DROP TABLE G_NAME;
DROP TABLE G_PARAMETERS;
DROP TABLE W_JOB_CHANGE_DATA;
DROP TABLE W_FINANCIAL_SUMMARY_COST_F;
DROP TABLE W_FINANCIAL_SUMMARY_SALES_F;
DROP TABLE W_INVOICELINE_F;
DROP TABLE W_JOB_SHIPMENT_F;
DROP TABLE W_SUB_JOB_F;
DROP TABLE W_JOB_F;
DROP TABLE W_LEAD_F;
DROP TABLE W_MACHINE_TYPE_D;
DROP TABLE W_LOCATION_D;
DROP TABLE W_TIME_D;
DROP TABLE W_SALES_CLASS_D;
DROP TABLE W_SALES_AGENT_D;
DROP TABLE W_CUST_LOCATION_D;
DROP TABLE W_CUSTOMER_D;
DROP TABLE W_ERROR_LOG;
DROP TABLE G_COMPANY;

-- drop existing sequences...

DROP SEQUENCE W_CUSTOMER_D_SEQ;
DROP SEQUENCE W_CUST_LOCATION_D_SEQ;
DROP SEQUENCE W_SALES_AGENT_D_SEQ;
DROP SEQUENCE W_SALES_CLASS_D_SEQ;
DROP SEQUENCE W_LOCATION_D_SEQ;
DROP SEQUENCE W_MACHINE_TYPE_D_SEQ;
DROP SEQUENCE W_LEAD_F_SEQ;
DROP SEQUENCE W_JOB_F_SEQ;
DROP SEQUENCE W_SUB_JOB_F_SEQ;
DROP SEQUENCE W_JOB_SHIPMENT_F_SEQ;
DROP SEQUENCE W_INVOICELINE_F_SEQ;
DROP SEQUENCE W_JOB_CHANGE_DATA_SEQ;




