SET serveroutput ON;
SET serveroutput ON;
--EXEC deleteAll_F;
CREATE INDEX "INVOICE_CUST_KEY" ON "W_INVOICELINE_F"
  (
    "CUST_KEY",
    "INVOICE_ID"
  ) ;
CREATE INDEX "SUB_PROD_END" ON "W_SUB_JOB_F"
  (
    "DATE_PROD_END"
  ) ;
EXEC LEAD_JOB_SUB_SHIP_F_GEN(50,20130102,20141231,0);
CREATE INDEX "INVOICELINE" ON "W_INVOICELINE_F"
  (
    "SALES_CLASS_ID",
    "LOCATION_ID",
    "INVOICE_DUE_DATE"
  ) ;
CREATE INDEX "SUBJOIB" ON "W_SUB_JOB_F"
  (
    "SALES_CLASS_ID",
    "LOCATION_ID",
    "MACHINE_TYPE_ID"
  ) ;
EXEC W_FINANC_SUM_SALES_D_GEN(85);
EXEC W_FINANC_SUM_COST_D_GEN(15);
DROP INDEX "INVOICELINE";
DROP INDEX "SUBJOIB";
DROP INDEX "INVOICE_CUST_KEY";
DROP INDEX "SUB_PROD_END";
EXEC fact_Count;